### ISSUE TITLE
Step 3 needs "cd /home/ubuntu"

### ISSUE THREAD

**Issue by tabernarious** [MattDierick/RTD-NGINX-App-Protect-UDF#13]
As in Step 1, I would recommend Step 3 include the tip to "cd /home/ubuntu" either in-line or as an additional step. Even if using SSH automatically drops you in /home/ubuntu, the "cd /home/ubuntu" should do no harm.

Step 1 (current):
SSH (or WebSSH and cd /home/ubuntu/) to CICD Server

Step 3 (current):
SSH to Docker App Protect + Docker repo VM

Step 3 (recommended):
SSH (or WebSSH and cd /home/ubuntu/) to Docker App Protect + Docker repo VM

*or*

SSH to Docker App Protect + Docker repo VM
cd /home/ubuntu

**Comment by MattDierick** [comment]
Thanks, good catch :) Will update it ASAP.

**Comment by MattDierick** [comment]
Fixed. Thanks
