### ISSUE TITLE
nginx -s reload

### ISSUE THREAD

**Issue by jessegoodier** [MattDierick/RTD-NGINX-App-Protect-UDF#16]
I would recommend changing the service restart command 
from systemctl restart nginx
to sudo nginx -s reload

the reload signal allows current connections to complete before stopping the current worker processes.
I see many people doing the service restart and not realize there's a better way.

**Comment by jessegoodier** [comment]
on this step: https://github.com/MattDierick/RTD-NGINX-App-Protect-UDF/blob/master/source/class3/module1/module1.rst

**Comment by MattDierick** [comment]
Thanks for this very useful comment. I will follow your advise and update the doc.

**Comment by MattDierick** [comment]
Fixed, thanks. I keep the "service restart" for the first installation (package) and move to Reload for signatures and TC.
