### ISSUE TITLE
Step 7: Customize the WAF Policy - Site Can't Be Reached error

### ISSUE THREAD

**Issue by honghuac** [MattDierick/RTD-NGINX-App-Protect-UDF#18]
Hi Matt

Great demo. However, I need help troubleshooting this issue.

In **Step 7: Customize the WAF Policy**, *Instruction* _8. RDP to the Jumphost as user:user and click on bookmark Arcadia NAP Docker_ results in the following **Site Can't Be Reached** error

![arc-nap](https://user-images.githubusercontent.com/8625482/97129687-81704680-177a-11eb-9bbd-877223beebbd.PNG)

The services and pods are running.

![ku](https://user-images.githubusercontent.com/8625482/97130254-dc566d80-177b-11eb-944f-2fecc873f09b.PNG)

**Comment by MattDierick** [comment]
Let's sync offline on Teams. I sync it is an issue in your lab. The docker is not runnning.

**Comment by honghuac** [comment]
I found the root cause of the issue. Wrongly named policy file. Issue closed.
