### ISSUE TITLE
[Step 10 - Deploy App Protect via CI/CD Pipeline] Missing stage in Jenkinsfile

### ISSUE THREAD

**Issue by honghuac** [MattDierick/RTD-NGINX-App-Protect-UDF#19]
Hi Matt,

The Jenkinspipeline shown in the instructions **Step 10 - Deploy App Protect via CI/CD Pipeline** does not exactly match the Jenkinspipeline in the Gitlab repository **NGINX App Protect**.

![jenkinsfile](https://user-images.githubusercontent.com/8625482/97585230-de4a5600-1a33-11eb-9c64-f0b25b0685d6.PNG)

The stage **"Deploy NGINX Plus"** is missing.

**Comment by MattDierick** [comment]
Thanks mate :) Good catch.

**Comment by MattDierick** [comment]
Fixed : https://github.com/MattDierick/RTD-NGINX-App-Protect-UDF/commit/811f30d783bd9abe042af6348350cc1a1520a531
