### ISSUE TITLE
Step 11 - Deploy a new version of the NGINX Plus Ingress Controller - error after pushing of new version of KIC

### ISSUE THREAD

**Issue by honghuac** [MattDierick/RTD-NGINX-App-Protect-UDF#20]
In **Step 11 - Deploy a new version of the NGINX Plus Ingress Controller**

The following errors (highlighted in yellow) occur after the rollout of the new version of KIC, that has app protection.

![err](https://user-images.githubusercontent.com/8625482/97589018-063bb880-1a38-11eb-9e71-7d00debfcee9.PNG)

**Comment by MattDierick** [comment]
I guess v2.1. They change the  version / v1beta1. I need to force v2.0 install till I fix it.

**Comment by MattDierick** [comment]
I can't reproduice it. Did you delete the previous KIC ? 

kubectl delete -f /home/ubuntu/k8s_ingress/full_ingress_arcadia.yaml
