### ISSUE TITLE
TC - NMAP detected as Bot

### ISSUE THREAD

**Issue by erkac** [MattDierick/RTD-NGINX-App-Protect-UDF#27]
Hi Matthieu,

the TC part of the demo is a bit shaky, those request are also recognized as malicious using the Attack Signatures. On top of it in the latest release v40, the NMAP HEAD request is blocked as _Bot Client Detected_ not as the _TC_ attack.
Is there any chance to get better examples for TC attacks from our F5 Labs folks?

<img width="1691" alt="logs" src="https://user-images.githubusercontent.com/5064350/99511912-28ff2400-2989-11eb-8946-2a7938d5cefb.png">

Thanks.
Lubos Klokner

**Comment by MattDierick** [comment]
Thanks for the head up Lubos. Unfortunatly, it is very difficult to keep the TC attacks up to date. I have access to the TC server, I will grab a new attack rule :)

**Comment by MattDierick** [comment]
Lab updated. Will add new attacks asap in the collection.
