### ISSUE TITLE
Update in Postman config needed

### ISSUE THREAD

**Issue by zollerp** [MattDierick/RTD-NGINX-App-Protect-UDF#5]
Hi,

in "https://rtd-nginx-app-protect-udf.readthedocs.io/en/latest/class2/module3/module3.html" ou are reffering to "Simulate a Threat Campaign attack"

Within Postman, please change from „http://app-protect-centos.arcadia-finance.io" to “http://app-protect.arcadia-finance.io"

Cheers

**Comment by MattDierick** [comment]
Fixed in UDF version 23
